### ISSUE TITLE
Support gradle wrapper

### ISSUE THREAD

**Issue by abeggchr** [abeggchr/cake-gradle#5]
A gradle wrapper (the gradlew.bat /gradlew file in the /example) directory is not used but only the gradle.bat/gradle from the PATH.

Expected behavior: use the wrapper from the project directory if available.

**Comment by abeggchr** [comment]
pseudo code
```
var executableFile = isOnWindowsPlattform ? "gradle.bat" : "gradle";
var isGradleWrapperAvailable = File.Exists(projectDirectory + executableFile );
if (isGradleWrapperAvailable) {
   // use the wrapper from the project directory
   return projectDirectory + executableFile; 
} else {
   // use the globally installed gradle executable
   return executableFile;
}
```

**Comment by phillipsj** [comment]
That is one way to do it for sure.  You could also add a custom tool locater.  You can see one of those in the Cake repo or in my repo for Cake.AppPackager.  When I get a chance to sit at a computer I can add son more detail.  I need to do something similar for Cake.Netlify just so users don't have to specify the local path in the settings file.  You can always ovverride the tool path using the tool settings if you didint know.

**Comment by phillipsj** [comment]
I also forgot,  you can just add your custom logic by overriding GetAlternativePaths on your tool using your logic.

**Comment by abeggchr** [comment]
Thanks for the hint about GetAlternativePaths(). Implemented in: https://github.com/abeggchr/cake-gradle/blob/feature/%233-support-gradle-wrapper/src/Cake.Gradle/GradleRunner.cs (line 59).

Gradle wrapper (gradlew.bat from working directory) is now supported when no "gradle.bat" executable is found in the system PATH. 

If there is a "gradle.bat" executable in the system PATH, this is prefered over the "gradlew.bat". How can I change this behavior? I want to prefer "gradlew.bat" over "gradle.bat"?

**Comment by phillipsj** [comment]
I think the order they are entered matters so put the ones you prefer first
in the list.

**Comment by abeggchr** [comment]
Looking at `Tools.cs`:
a) GetToolPathObsolete -> there is a predefined order of 1) use tool from /tools/** 2) use from PATH 3) use from alternative paths (but named "obsolete")
b) GetToolPathUsingToolService -> a toolservice is used, didn't get this one

But found another way to achieve the desired behavior. Thanks
